FROM ubuntu
 
RUN apt update
RUN apt -y install dpkg-dev
RUN apt -y install gcc
RUN apt -y install g++
RUN apt -y install cmake
RUN apt -y install gdb
RUN apt -y install libboost-all-dev
RUN apt -y install net-tools
RUN apt -y install iputils-ping


CMD ["bash"]